name: sort_it
description: A waste management application built using flutter.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.7
  country_code_picker: ^2.0.2
  dio: ^4.0.4
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.8
  flutter_screenutil: ^5.1.1
  font_awesome_flutter: ^9.2.0
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  firebase_storage: ^10.2.6
  get: ^4.6.1
  image_picker: ^0.8.4+9
  lottie: ^1.2.1
  permission_handler: ^8.3.0
  pretty_dio_logger: ^1.1.1
  qr_code_scanner: ^0.6.1
  qr_flutter: ^4.0.0
  sms_autofill: ^2.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.3.3
flutter_native_splash:
  color: "#22343C"
  image: assets/images/splash_1024.png
  android: true
  ios: true

  #flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/splash/
    - assets/lottie/
    - assets/icons/

  fonts:
    - family: "abzi" #ABeeZee-Italic
      fonts:
        - asset: "assets/fonts/ABeeZee-Italic.ttf"
          style: "normal"
          weight: 400
    - family: "abzr" #ABeeZee-Regular
      fonts:
        - asset: "assets/fonts/ABeeZee-Regular.ttf"
          style: "normal"
          weight: 400

